name: careercheckr
description: "A Flutter app to detect fake internships and job scams."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  http: ^0.13.6
  provider: ^6.1.1
  percent_indicator: ^4.2.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.7
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env